CREATE TABLE [dbo].[FROM_CONFIG] (
    [TRANSPORT_ID]        VARCHAR (10)  NULL,
    [TRANSPORT_PASSWORD]  VARCHAR (45)  NULL,
    [PARTY_ID]            VARCHAR (10)  NOT NULL,
    [PARTY_DESCRIPTION]   VARCHAR (200) NULL,
    [ROUTING_ID]          VARCHAR (39)  NULL,
    [ROUTING_DESCRIPTION] VARCHAR (200) NULL,
    [SIGN_ID]             VARCHAR (4)   NULL,
    [SUBSTITUTE_PARTY_ID] VARCHAR (10)  NULL,
    CONSTRAINT [FROM_CONFIG_PK1] UNIQUE NONCLUSTERED ([PARTY_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FROM_CONFIG_INDEX1]
    ON [dbo].[FROM_CONFIG]([SUBSTITUTE_PARTY_ID] ASC);

