CREATE TABLE [dbo].[SCHEDULE_CONFIG] (
    [TASK]            VARCHAR (30) NOT NULL,
    [ENABLE]          VARCHAR (1)  NULL,
    [SCHEDULE_TYPE]   VARCHAR (10) NULL,
    [SCHEDULE_WEEK]   VARCHAR (15) NULL,
    [SCHEDULE_TIME]   VARCHAR (50) NULL,
    [SCHEDULE_PERIOD] VARCHAR (10) NULL,
    [SCHEDULE_RANGE]  VARCHAR (15) NULL,
    CONSTRAINT [SCHEDULE_CONFIG_PK1] UNIQUE NONCLUSTERED ([TASK] ASC)
);

