CREATE TABLE [dbo].[SIGN_CONFIG] (
    [SIGN_ID]       VARCHAR (4)   NOT NULL,
    [SIGN_TYPE]     VARCHAR (10)  DEFAULT (NULL) NULL,
    [PFX_PATH]      VARCHAR (100) DEFAULT (NULL) NULL,
    [SIGN_PASSWORD] VARCHAR (60)  DEFAULT (NULL) NULL,
    CONSTRAINT [SIGN_CONFIG_PK1] UNIQUE NONCLUSTERED ([SIGN_ID] ASC)
);

