CREATE TABLE [dbo].[TASK_CONFIG] (
    [CATEGORY_TYPE]      VARCHAR (5)   NOT NULL,
    [PROCESS_TYPE]       VARCHAR (10)  NOT NULL,
    [TASK]               VARCHAR (15)  NOT NULL,
    [SRC_PATH]           VARCHAR (200) NULL,
    [TARGET_PATH]        VARCHAR (200) NULL,
    [FILE_FORMAT]        VARCHAR (20)  NULL,
    [VERSION]            VARCHAR (5)   NULL,
    [ENCODING]           VARCHAR (15)  NULL,
    [TRANS_CHINESE_DATE] VARCHAR (1)   NULL,
    CONSTRAINT [TASK_CONFIG_PK1] UNIQUE NONCLUSTERED ([CATEGORY_TYPE] ASC, [PROCESS_TYPE] ASC, [TASK] ASC)
);

