CREATE TABLE [dbo].[TO_CONFIG] (
    [PARTY_ID]            VARCHAR (10)  NOT NULL,
    [PARTY_DESCRIPTION]   VARCHAR (200) NULL,
    [ROUTING_ID]          VARCHAR (39)  NULL,
    [ROUTING_DESCRIPTION] VARCHAR (200) NULL,
    [FROM_PARTY_ID]       VARCHAR (10)  NULL,
    CONSTRAINT [TO_CONFIG_PK1] UNIQUE NONCLUSTERED ([FROM_PARTY_ID] ASC, [PARTY_ID] ASC)
);

