CREATE TABLE [dbo].[TURNKEY_MESSAGE_LOG_DETAIL] (
    [SEQNO]       VARCHAR (8)   NOT NULL,
    [SUBSEQNO]    VARCHAR (5)   NOT NULL,
    [PROCESS_DTS] VARCHAR (17)  NULL,
    [TASK]        VARCHAR (30)  NOT NULL,
    [STATUS]      VARCHAR (5)   NULL,
    [FILENAME]    VARCHAR (300) NULL,
    [UUID]        VARCHAR (40)  NULL,
    CONSTRAINT [TURNKEY_MESSAGE_LOG_DETAIL_PK1] UNIQUE NONCLUSTERED ([SEQNO] ASC, [SUBSEQNO] ASC, [TASK] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TURNKEY_MESSAGE_LOG_DETAIL_INDEX1]
    ON [dbo].[TURNKEY_MESSAGE_LOG_DETAIL]([FILENAME] ASC);

