CREATE TABLE [dbo].[TURNKEY_USER_PROFILE] (
    [USER_ID]       VARCHAR (10)  NOT NULL,
    [USER_PASSWORD] VARCHAR (100) NOT NULL,
    [USER_ROLE]     VARCHAR (2)   NULL,
    CONSTRAINT [TURNKEY_USER_PROFILE_PK1] UNIQUE NONCLUSTERED ([USER_ID] ASC)
);

