CREATE TABLE [dbo].[TURNKEY_TRANSPORT_CONFIG] (
    [TRANSPORT_ID]       VARCHAR (10) NOT NULL,
    [TRANSPORT_PASSWORD] VARCHAR (60) NOT NULL,
    CONSTRAINT [TURNKEY_TRANSPORT_CONFIG_PK1] UNIQUE NONCLUSTERED ([TRANSPORT_ID] ASC)
);

