CREATE TABLE [dbo].[TURNKEY_SYSEVENT_LOG] (
    [EVENTDTS]     VARCHAR (17)  NOT NULL,
    [PARTY_ID]     VARCHAR (10)  NULL,
    [SEQNO]        VARCHAR (8)   NULL,
    [SUBSEQNO]     VARCHAR (5)   NULL,
    [ERRORCODE]    VARCHAR (4)   NULL,
    [UUID]         VARCHAR (40)  NULL,
    [INFORMATION1] VARCHAR (100) NULL,
    [INFORMATION2] VARCHAR (100) NULL,
    [INFORMATION3] VARCHAR (100) NULL,
    [MESSAGE1]     VARCHAR (100) NULL,
    [MESSAGE2]     VARCHAR (100) NULL,
    [MESSAGE3]     VARCHAR (100) NULL,
    [MESSAGE4]     VARCHAR (100) NULL,
    [MESSAGE5]     VARCHAR (100) NULL,
    [MESSAGE6]     VARCHAR (100) NULL,
    CONSTRAINT [TURNKEY_SYSEVENT_LOG_PK1] UNIQUE NONCLUSTERED ([EVENTDTS] ASC)
);


GO
CREATE NONCLUSTERED INDEX [TURNKEY_SYSEVENT_LOG_INDEX1]
    ON [dbo].[TURNKEY_SYSEVENT_LOG]([SEQNO] ASC, [SUBSEQNO] ASC);


GO
CREATE NONCLUSTERED INDEX [TURNKEY_SYSEVENT_LOG_INDEX2]
    ON [dbo].[TURNKEY_SYSEVENT_LOG]([UUID] ASC);

